package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

// netTemplateInfix marks the variant of a jail template used when the service
// is on a network of its own rather than on the host's stack.
const netTemplateInfix = ".net"

// netTemplateHeader opens every generated variant. The file is fjord's, not
// the bundle's, and editing it is pointless -- the next save writes it again.
const netTemplateHeader = `# Generated by fjord from the template of the same name without ".net".
# The same jail, minus ip4/ip6: this service is on a network of its own, and a
# vnet jail may not have those parameters set at all. Edit the original.

`

// jailAddressParam matches the jail parameters that say which network stack a
// jail gets: ip4/ip6 and the ip4.addr/ip6.addr family.
//
// It is SETTING one of these that jail(8) refuses next to vnet, not the value:
// "vnet jails cannot have IP address restrictions" comes of the parameter
// being present at all. Which is why immich's three templateless jails
// attached fine and its database -- the one service with a template, ending
// `ip4: inherit` -- would not start. Leaving the parameters out gives a vnet
// jail ip4=inherit anyway, so the variant loses nothing.
var jailAddressParam = regexp.MustCompile(`^[[:space:]]*(ip4|ip6)([.][[:alnum:]_.]+)?[[:space:]]*([:=].*)?;?[[:space:]]*$`)

// stripJailAddressing returns a jail template with its host-addressing
// parameters removed and everything else -- sysvmsg/sysvsem/sysvshm, mounts,
// exec lines, comments -- kept exactly as it was.
func stripJailAddressing(body string) string {
	lines := strings.Split(body, "\n")
	out := lines[:0]
	for _, line := range lines {
		if jailAddressParam.MatchString(line) {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// netTemplateName is the file name of a template's networked variant:
// immich-postgres-template.conf -> immich-postgres-template.net.conf.
func netTemplateName(name string) string {
	if isNetTemplateName(name) {
		return name
	}
	ext := filepath.Ext(name)
	return strings.TrimSuffix(name, ext) + netTemplateInfix + ext
}

// baseTemplateName is netTemplateName's inverse, and the identity for a name
// that is already the base one.
func baseTemplateName(name string) string {
	if !isNetTemplateName(name) {
		return name
	}
	ext := filepath.Ext(name)
	if ext == netTemplateInfix {
		return strings.TrimSuffix(name, ext) // a template with no extension
	}
	return strings.TrimSuffix(strings.TrimSuffix(name, ext), netTemplateInfix) + ext
}

func isNetTemplateName(name string) bool {
	ext := filepath.Ext(name)
	return ext == netTemplateInfix || strings.HasSuffix(strings.TrimSuffix(name, ext), netTemplateInfix)
}

// directorTemplateRefs lists, by base file name, every jail template the
// document references -- at the project level or in a service. Names are
// normalized to the base variant, so it answers the same thing whether the
// stack is currently attached or not.
func directorTemplateRefs(root *yaml.Node) []string {
	seen := map[string]bool{}
	var out []string
	forEachTemplateOption(root, func(val *yaml.Node) {
		name := baseTemplateName(filepath.Base(val.Value))
		if name == "" || name == "." || name == "/" || seen[name] {
			return
		}
		seen[name] = true
		out = append(out, name)
	})
	return out
}

// retargetTemplates points every template reference under n at the networked
// variant, or back at the base one. Only the file name changes: the !ENV tag
// and the ${PWD} that makes the path relative to the stack dir are the node's
// and are left alone.
func retargetTemplates(n *yaml.Node, toNet bool) {
	forEachTemplateOption(n, func(val *yaml.Node) {
		dir, file := filepath.Split(val.Value)
		if toNet {
			file = netTemplateName(file)
		} else {
			file = baseTemplateName(file)
		}
		val.Value = dir + file
	})
}

// forEachTemplateOption visits the value node of every `- template: <path>`
// option in n's own `options:` list and in each of its services'.
func forEachTemplateOption(n *yaml.Node, fn func(val *yaml.Node)) {
	if n == nil {
		return
	}
	visit := func(owner *yaml.Node) {
		opts := mapKey(owner, "options")
		if opts == nil || opts.Kind != yaml.SequenceNode {
			return
		}
		for _, item := range opts.Content {
			if item.Kind == yaml.MappingNode && len(item.Content) >= 2 &&
				item.Content[0].Value == "template" &&
				item.Content[1].Kind == yaml.ScalarNode && item.Content[1].Value != "" {
				fn(item.Content[1])
			}
		}
	}
	visit(n)
	if services := mapKey(n, "services"); services != nil && services.Kind == yaml.MappingNode {
		for i := 1; i < len(services.Content); i += 2 {
			visit(services.Content[i])
		}
	}
}

// writeNetTemplates materializes the networked variant of each named template
// next to the original in dir.
//
// Both variants are written up front, so putting a service on a network or
// taking it off is a string in the director and never a file that has to be
// created at the same time -- including for a stack whose bundle was written
// before this existed, since the caller passes what the director references
// and the source is read back from disk.
func writeNetTemplates(dir string, names []string) error {
	for _, name := range names {
		if name != filepath.Base(name) || strings.HasPrefix(name, ".") {
			return fmt.Errorf("refusing template name %q", name)
		}
		// A bundle that ships its own foo.net.conf owns that file; generating
		// over it would replace a real template with a derived one.
		if isNetTemplateName(name) {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			if os.IsNotExist(err) {
				continue // referenced but not shipped -- appjail says so, not fjord
			}
			return err
		}
		// The header says what this file is, because the comments it inherits
		// explain lines it no longer has -- the base template's own paragraph
		// about why ip4 is set there reads as a lie in the copy without it.
		out := netTemplateHeader + strings.TrimLeft(stripJailAddressing(string(body)), "\n")
		out = strings.TrimRight(out, "\n") + "\n"
		if err := os.WriteFile(filepath.Join(dir, netTemplateName(name)), []byte(out), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// ensureNetTemplates is writeNetTemplates for a stack dir whose director is
// already on disk: it reads what the document references and generates the
// variants for it.
func ensureNetTemplates(dir, directorYML string) error {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(directorYML), &doc); err != nil {
		return nil // not a director fjord can read; nothing to generate
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		return nil
	}
	return writeNetTemplates(dir, directorTemplateRefs(doc.Content[0]))
}
